name: Setup
description: "Install required dependencies and build site"

inputs:
  hugo-version:
    description: "Hugo version"
    required: true
    default: "0.126.1"
  node-version:
    description: "Node version"
    required: true
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Setup Hugo ${{ inputs.hugo-version }}
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/hugo_extended_${{ inputs.hugo-version }}_linux-amd64.deb
        sudo dpkg -i ${{ runner.temp }}/hugo.deb
      shell: bash
    - name: Set up pnpm ${{ inputs.pnpm-version }}
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4
    - name: Set up Node ${{ inputs.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Install Playwright browsers
      run: pnpm playwright install --with-deps
      shell: bash
    - name: Install PostCSS globally
      run: npm install -g postcss-cli
      shell: bash
    - name: Install Lighthouse globally
      run: npm install -g @lhci/cli
      shell: bash
