name: Build

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run e2e tests
        run: pnpm test:e2e
      - name: Build
        run: |
          pnpm build \
            --baseURL "https://myopic.design/" \
            --destination "public"
      - name: Run Lighthouse tests
        run: pnpm test:lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload website
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: website
          path: public
          retention-days: 1
      - name: Upload e2e test reports
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: ${{ always() }}
        with:
          name: e2e-reports
          path: |
            e2e-report/
            e2e-results/
          retention-days: 7
